import type { Metadata } from 'next';
import { Oxanium, Poppins } from 'next/font/google';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from 'components/navbar';

export const metadata: Metadata = {
	title: 'Destiny',
	description: 'Generated by create next app'
};

const oxanium = Oxanium({
	weight: ['400', '500', '600', '700', '800'],
	style: ['normal'],
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-oxanium'
});

const poppins = Poppins({
	weight: ['400', '500', '600', '700', '800'],
	style: ['normal'],
	subsets: ['latin'],
	display: 'swap'
});

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${poppins.className} ${oxanium.variable}`}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
